name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: daaku/gh-action-apt-install@92eea4f84f90c895b544aaec6ae21839127c84e5
      with:
        packages: libsdl2-dev
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      if: ${{ github.event_name == 'push' }}
      with:
        name: byte-pusher-emu
        path: target/release/byte-pusher-emu
        if-no-files-found: error
        overwrite: false
